name: .NET Core CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore src/ServiceA/TicketBooking.sln

    - name: Build
      run: dotnet build src/ServiceA/TicketBooking.sln --no-restore

    - name: Run Unit Tests
      run: dotnet test src/ServiceA/TicketBooking.sln --no-build --verbosity normal